// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // WISeAgentSidebar: [{type: 'autogenerated', dirName: '.'}], // Commenting out or removing this line

  // Manually defined sidebar to control top-level order
  WISeAgentSidebar: [
    {
      type: 'category',
      label: 'GenAI',
      link: {
        type: 'generated-index',
        title: 'Generative AI'
      },
      items: [{type: 'autogenerated', dirName: 'GenAI'}],
    },
    {
      type: 'category',
      label: 'TechSavvy',
      link: {
        type: 'generated-index',
        title: 'Tech Savvy'
      },
      items: [{type: 'autogenerated', dirName: 'TechSavvy'}],
    },
    {
      type: 'category',
      label: 'AWS',
      link: {
        type: 'generated-index',
        title: 'AWS'
      },
      items: [{type: 'autogenerated', dirName: 'AWS'}],
    },
    {
      type: 'category',
      label: 'Docker',
      link: {
        type: 'generated-index',
        title: 'Docker'
      },
      items: [{type: 'autogenerated', dirName: 'docker'}],
    },
    {
      type: 'category',
      label: 'Lifestyle',
      link: {
        type: 'generated-index',
        title: 'Lifestyle'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Lifestyle/Recipes'
        },
        {
          type: 'autogenerated',
          dirName: 'Lifestyle/Drinks'
        },
        {
          type: 'autogenerated',
          dirName: 'Lifestyle/TastingNotes'
        }
      ],
    },
    {
      type: 'category',
      label: 'TravelHacks',
      link: {
        type: 'generated-index',
        title: 'Travel Hacks'
      },
      items: [{type: 'autogenerated', dirName: 'TravelHacks'}],
    },
    // {
    //   type: 'category',
    //   label: 'EverydayHacks',
    //   link: {
    //     type: 'generated-index',
    //     title: 'Everyday Hacks'
    //   },
    //   items: [{type: 'autogenerated', dirName: 'EverydayHacks'}],
    // },
  ],
};

module.exports = sidebars;
