name: Deploy to GitHub Pages

on:
    pull_request:
        types: [closed]
        branches: [main]

permissions:
    contents: write
    pages: write
    pull-requests: write

jobs:
  lint-and-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g markdownlint-cli
          npm install -g cspell

      - name: Spell Check
        run: cspell "**/*.{md,mdx}"

      - name: Markdown Lint
        run: markdownlint "**/*.md" --ignore node_modules

  delete-branch:
    needs: lint-and-test
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Delete Merged Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=$(echo ${{ github.event.pull_request.head.ref }})
          repo_full_name=$(echo ${{ github.repository }})
          curl -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$repo_full_name/git/refs/heads/$branch_name

  build-and-deploy:
      needs: [lint-and-test, delete-branch]
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Setup Node
            uses: actions/setup-node@v3
            with:
                node-version: 18
                cache: npm

          - name: Install Dependencies
            run: npm ci

          - name: Build Site
            run: npm run build

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build  # Docusaurus builds to ./build instead of ./docs
                publish_branch: gh-pages
                user_name: 'github-actions[bot]'
                user_email: 'github-actions[bot]@users.noreply.github.com'
                force: true