name: Deploy to GitHub Pages
on:
    pull_request:
        types: [closed]
        branches: [main]
    permissions:
        contents: write
        pages: write
#        id-token: write
jobs:
    build-and-deploy:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Build Site
              run: npx @11ty/eleventy
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public