name: Deploy to GitHub Pages
on:
    pull_request:
        types: [closed]
        branches: [main]
permissions:
    contents: write
    pages: write
    pull-requests: write
jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Delete Merged Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=$(echo ${{ github.event.pull_request.head.ref }})
          repo_full_name=$(echo ${{ github.repository }})
          curl -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$repo_full_name/git/refs/heads/$branch_name

  build-and-deploy:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Setup Node
            uses: actions/setup-node@v3
            with:
                node-version: 18
          - name: Install Dependencies
            run: npm install
          - name: Build Site
            run: npx @11ty/eleventy
          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs
                publish_mode: 'dir'